apiVersion: apps/v1
kind: Deployment
metadata:
  name: gpitfutures-bc-app-nginx
  namespace: buyingcatalogue-dev-mp
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  selector:
    matchLabels:
      app: gpitfutures-bc-app-nginx
  template:
    metadata:
      labels:
        app: gpitfutures-bc-app-nginx
    spec:
      imagePullSecrets:
      - name: devpipelinevariables
      containers:
      - name: gpitfutures-bc-app-nginx
        image: gpitfuturesdevacr.azurecr.io/nhsd/buying-catalogue/nginx/mp
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 250m
          limits:
            cpu: 500m
